package model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import model.Searches;

import model.SearchesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchesDaoConfig;

    private final SearchesDao searchesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchesDaoConfig = daoConfigMap.get(SearchesDao.class).clone();
        searchesDaoConfig.initIdentityScope(type);

        searchesDao = new SearchesDao(searchesDaoConfig, this);

        registerDao(Searches.class, searchesDao);
    }
    
    public void clear() {
        searchesDaoConfig.getIdentityScope().clear();
    }

    public SearchesDao getSearchesDao() {
        return searchesDao;
    }

}
